### ISSUE TITLE
Unable to install requirements on ubuntu/debian

### ISSUE THREAD

**Issue by javilinux** [blackeko/PEpper#1]
Hello,

While trying to install the requirements on Ubuntu 19.04 or Debian 9 I get the same error:
pip3 install -r requirements.txt
....
....
Collecting yara==3.10.0 (from -r requirements.txt (line 7))
  Could not find a version that satisfies the requirement yara==3.10.0 (from -r requirements.txt (line 7)) (from versions: 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7)        
No matching distribution found for yara==3.10.0 (from -r requirements.txt (line 7))

**Comment by thisguy23** [comment]
pip3 install -U git+https://github.com/VirusTotal/yara-python worked for me.

**Comment by kernel-pan-ic** [comment]
Same issue present on Arch Linux and likely many others.

**Comment by sec0ps** [comment]
$ pip3 install -U git+https://github.com/VirusTotal/yara-python
Collecting git+https://github.com/VirusTotal/yara-python
  Cloning https://github.com/VirusTotal/yara-python to /tmp/pip-cwrcpjkx-build
Installing collected packages: yara-python
  Running setup.py install for yara-python ... done
Successfully installed yara-python-3.10.0

$ pip3 install -r requirements.txt
Collecting pefile==2019.4.18 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/36/58/acf7f35859d541985f0a6ea3c34baaefbfaee23642cf11e85fe36453ae77/pefile-2019.4.18.tar.gz
Collecting yara_python==3.10.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/1d/93/688492dcedbd57a9c0b4074aa47d39ac5f5e7411a8ce69b23e57a801e638/yara-python-3.10.0.tar.gz
Collecting requests==2.22.0 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting lief==0.9.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/cd/0e/0d6f3357975dd1530aeb4b4a84a99d493775391758378fb5109f47b613f9/lief-0.9.0.zip
Collecting python_magic==0.4.15 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting modules==1.0.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/4b/95/2f306ff2299ed8d44fbabac4c0b193628c4c65398ed59af2db66b6f52632/modules-1.0.0.tar.gz
Collecting yara==3.10.0 (from -r requirements.txt (line 7))
  Could not find a version that satisfies the requirement yara==3.10.0 (from -r requirements.txt (line 7)) (from versions: 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7)
No matching distribution found for yara==3.10.0 (from -r requirements.txt (line 7))

**Comment by sneh-p** [comment]
Getting error on import of magic library.

![image](https://user-images.githubusercontent.com/53498094/63639071-8f4da780-c65d-11e9-87a5-74d0b9209220.png)
